name: Reportar Bug
description: Crie um relato de erro para nos ajudar a melhorar nossos sistemas.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: O que aconteceu de errado? Descreva o problema detalhadamente.
      placeholder: Exemplo - O script X não está salvando os dados no banco de dados.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Como reproduzir
      description: Quais são os passos para reproduzir este erro?
      placeholder: |
        1. Abra o painel...
        2. Clique no botão...
        3. Veja o erro na tela...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versão do Sistema/Resource
      description: Qual versão você está utilizando?
    validations:
      required: true